name: lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  reactci:
    name: reactci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Run linter
        run: yarn run lint
